dependencies:
  certificate-roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.11.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.11.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.1.0
